# Generated by Django 5.0.9 on 2024-10-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField()),
                ('session_id', models.IntegerField(max_length=6, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
