# Generated by Django 5.0.9 on 2024-10-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_quizscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizscore',
            name='username',
            field=models.CharField(blank=True),
        ),
    ]
