# Generated by Django 5.0.9 on 2024-10-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_quizscore_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('completed', 'Completed'), ('pending', 'Pending'), ('in progress', 'In Progress')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='session_id',
            field=models.IntegerField(unique=True),
        ),
    ]
